"use client"
import * as React from 'react';
import { Box } from '@mui/material';
import MenuLogo from '@/components/MenuLogo';
import MenuList from '@/components/MenuList';
import BoxMenuRightDash from '@/components/BoxMenuRightDash';
import Head from "next/head";

export default function dashpage() {
    return <Box >
        <Head>
            <title>Painel Memos App</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <Box className='main'>
            <Box className="left-menu">
                <Box className="menuLogo"><MenuLogo /></Box>
                <Box className="menuList"><MenuList /></Box>
            </Box>
            <Box className="right-dash" bgcolor="#d3d3d3">
                <Box>
                    <BoxMenuRightDash page="Painel" />
                </Box>
            </Box>
        </Box>;
    </Box>
}
