"use client"
import * as React from 'react';
import Head from "next/head";
import { Box, TextField } from "@mui/material";
import MenuList from "@/components/MenuList";
import MenuLogo from "@/components/MenuLogo";
import BoxMenuRightDash from "@/components/BoxMenuRightDash"
import UsersTable from "@/components/UsersTable"
import UserContainer from "@/containers/user";
import { useState } from "react";

export default function Home() {

  const { usersmemo } = UserContainer.useContainer()
  const [newUser, setNewUser] = useState()

  return (
    <>
      <Head>
        <title>Usuários Memos App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box className="main">
        <Box className="left-menu">
          <Box className="menuLogo"><MenuLogo /></Box>
          <Box className="menuList"><MenuList /></Box>
        </Box>
        <Box className="right-dash" bgcolor="#d3d3d3">
          <Box>
            <BoxMenuRightDash page="Usuários" />
          </Box>
          <Box className="tableusers">
            <UsersTable users={usersmemo} />
          </Box>
        </Box>
      </Box>
    </>
  );
}
