"use client"
import * as React from 'react';
import { Box, TextField } from '@mui/material';
import MenuLogo from '@/components/MenuLogo';
import MenuList from '@/components/MenuList';
import BoxMenuRightDash from '@/components/BoxMenuRightDash';
import Head from "next/head";
import MemosTablePage from '@/components/MemosTablePage';
import MemosContainer from '@/containers/memos';
import { useState } from "react";
import Modal from '@mui/material/Modal';
import BoxNewUser from '@/components/BoxNewUser';
import ButtonRegister from '@/components/ButtonRegister';

const style = {
    position: 'absolute',
    top: '50%',
    left: '50%',
    transform: 'translate(-50%, -50%)',
    width: 400,
    bgcolor: 'background.paper',
    border: '2px solid #000',
    boxShadow: 24,
    p: 4,
};


export default function Memospage() {

    const { memos, createMemo, getMemos } = MemosContainer.useContainer()

    const [newUser, setNewUser] = useState()

    const [open, setOpen] = React.useState(false)

    const handleOpen = (post: any) => {
        setNewUser(post)
        setOpen(true);
    }

    const handleClose = () => setOpen(false);

    const [memoUser, setMemoUser] = useState({
        nome: '',
        code: ''
    })

    const changeInput = (e: any) => {
        const newmemo = {
            ...memoUser,
            [e.target.name]: e.target.value
        }
        setMemoUser(newmemo)
    }

    console.log(newUser)

    const submitMemo = () => {
        createMemo(memoUser)
        handleClose()
        getMemos()
    }

    return <Box>
        <Head>
            <title>Memos App</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <Box className='main'>
            <Box className="left-menu">
                <Box className="menuLogo"><MenuLogo /></Box>
                <Box className="menuList"><MenuList /></Box>
            </Box>
            <Box className="right-dash" bgcolor="#d3d3d3">
                <Box>
                    <BoxMenuRightDash page="Memos" />
                </Box>
                <Box>
                    <BoxNewUser onClick={handleOpen} />
                </Box>
                <Modal
                    open={open}
                    onClose={handleClose}
                    aria-labelledby="modal-modal-title"
                    aria-describedby="modal-modal-description"
                >
                    <Box sx={style}>
                        <Box sx={{ backgroundColor: '', display: 'flex', gap: '20px', flexDirection: 'column', alignItems: 'center' }}>
                            <TextField id="standard-basic" label='Nome' name='nome' onChange={changeInput} value={memoUser.nome}></TextField>
                            <TextField id="standard-basic" label='Código' name='code' onChange={changeInput} value={memoUser.code}></TextField>
                            <Box>
                            </Box>   <ButtonRegister onClick={() => { submitMemo() }} />
                        </Box>
                    </Box>
                </Modal>
                <Box sx={{ height: 400, display: 'flex', width: '100%' }}>
                    <MemosTablePage memos={memos}></MemosTablePage>
                </Box>
            </Box>
        </Box>;
    </Box>
}
