"use client"
import * as React from 'react';
import { Box } from '@mui/material';
import MenuLogo from '@/components/MenuLogo';
import MenuList from '@/components/MenuList';
import BoxMenuRightDash from '@/components/BoxMenuRightDash';
import Head from "next/head";
import PostsContainer from '@/containers/posts';
import ActionAreaCard from '@/components/CardPosts';
import { useState } from 'react';
import Button from '@mui/material/Button';
import Typography from '@mui/material/Typography';
import Modal from '@mui/material/Modal';
import DeleteIcon from '@mui/icons-material/Delete';
import EditIcon from '@mui/icons-material/Edit';

const style = {
    position: 'absolute',
    top: '50%',
    left: '50%',
    transform: 'translate(-50%, -50%)',
    width: 400,
    bgcolor: 'background.paper',
    border: '2px solid #000',
    boxShadow: 24,
    p: 4,
};

export default function postspage() {
    const { postsmemo, deletePostsmemo } = PostsContainer.useContainer()
    const [postSelected, setPostSelected] = useState()

    const [open, setOpen] = React.useState(false);

    const handleOpen = (post: any) => {
        setPostSelected(post)
        setOpen(true);
    }

    const handleClose = () => setOpen(false);

    console.log(postSelected)

    return <Box>
        <Head>
            <title>Publicações Memos App</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <Box className='main'>
            <Box className="left-menu">
                <Box className="menuLogo"><MenuLogo /></Box>
                <Box className="menuList"><MenuList /></Box>
            </Box>
            <Box className="right-dash" bgcolor="#d3d3d3">
                <Box>
                    <BoxMenuRightDash page="Publicações" />
                </Box>
                <Box
                    sx={{ display: 'flex', flexWrap: 'wrap', gap: '15px', justifyContent: 'center', maxHeight: "600px", overflowY: 'scroll', paddingTop: '20px' }}>
                    {postsmemo.map((caracter) => {
                        return (
                            <ActionAreaCard photoUrl={caracter.photoUrl} user={caracter.user.name} onClick={() => handleOpen(caracter)} ></ActionAreaCard>
                        )
                    })}
                </Box>
                <Modal
                    open={open}
                    onClose={handleClose}
                >
                    <Box sx={style} >
                        <Box sx={{ display: 'flex', flexWrap: 'wrap', gap: '15px', justifyContent: 'center', maxHeight: "600px", overflowY: 'scroll', paddingTop: '20px' }}>
                            {postSelected && <ActionAreaCard photoUrl={postSelected.photoUrl} user={postSelected.user.name}></ActionAreaCard>}
                            <Box display='flex' flexDirection='column' gap='10px'>
                                <Box
                                    onClick={() => { deletePostsmemo(postSelected.id) }}
                                ><DeleteIcon sx={{ color: 'grey' }}></DeleteIcon></Box>
                                <Box><EditIcon sx={{ color: 'grey' }}></EditIcon></Box>
                            </Box>
                        </Box>
                    </Box>
                </Modal>
            </Box>
        </Box>
    </Box>;
}
